Repository MJU-Developers/23-W-JS-Study, pull requests merged in 2023-02, with the labels that each got.

#3 2주차-모유경
  youkyeong/ch10/README.md
  youkyeong/ch11/README.md
  youkyeong/ch12/README.md
  youkyeong/ch13/README.md
  youkyeong/ch14/README.md
  youkyeong/ch15/README.md
Labels: 2주차, 정리

#5 2주차 - 양채연
  .DS_Store
  양채연/.DS_Store
  양채연/1주차/chapter1.md
  양채연/1주차/chapter2.md
  양채연/1주차/chapter3.md
  양채연/1주차/chapter4.md
  양채연/1주차/chapter5.md
  양채연/1주차/chapter6.md
  양채연/1주차/chapter7.md
  양채연/1주차/chapter8.md
  양채연/1주차/chapter9.md
  양채연/2주차/chapter10.md
  양채연/2주차/chapter11.md
  양채연/2주차/chapter12.md
  양채연/2주차/chapter13.md
  양채연/2주차/chapter14.md
  양채연/2주차/chapter15.md
Labels: 2주차, 정리

#7 2주차-김태강
  taekang/ch10/README.md
  taekang/ch11/README.md
  taekang/ch12/README.md
  taekang/ch13/README.md
  taekang/ch14/README.md
  taekang/ch15/README.md
Labels: 2주차, 정리

#12 4주차 - 김보겸
  bokyeom/ch21/READMD.md
  bokyeom/ch22/README.md
  bokyeom/ch23/README.md
  bokyeom/ch24/README.md
  bokyeom/ch25/README.md
Labels: 4주차, 정리

#14 3주차-모유경
  youkyeong/ch16/README.md
  youkyeong/ch17/README.md
  youkyeong/ch18/README.md
  youkyeong/ch19/README.md
  youkyeong/ch20/README.md
Labels: 3주차, 정리
